### ISSUE TITLE
bsSuggest is not a function

### ISSUE THREAD

**Issue by bibyzhang** [lzwme/bootstrap-suggest-plugin#1]
hi,使用的时候发现这个错误, bootstrap-suggest.js 已引入
![qq20150918-1 2x](https://cloud.githubusercontent.com/assets/3280657/9950989/981ffb5a-5df3-11e5-8c05-643917cbc39e.png)

**Comment by renxia** [comment]
检查一下，应该是没有正确的引入，或者是在插件还未加载之前就开始了初始化动作

**Comment by bibyzhang** [comment]
thanks,问题解决了,我是用 jquery-1.11.3.min.js 这个版本的 jquery 时出的错误,换个版本就正常了
