### ISSUE TITLE
调用destroy 方法报错

### ISSUE THREAD

**Issue by wode551120** [lzwme/bootstrap-suggest-plugin#10]
Cannot read property 'slice' of undefined

将[].prototype.slice.call(arguments, 1)
改为
Array.prototype.slice.call(arguments, 1)
可以解决。

**Comment by renxia** [comment]
什么浏览器以及版本下？

**Comment by wode551120** [comment]
360极速浏览器8.5版本。内核版本45。

**Comment by renxia** [comment]
既然是 极速模式，应该不会有这样的问题，你访问 demo 页面时也会如此报错吗

http://lzw.me/pages/demo/bootstrap-suggest-plugin/demo/

**Comment by wode551120** [comment]
访问demo没问题，不过你demo好像并没有调用destroy 方法。

**Comment by renxia** [comment]
恩，是的，仔细看了下，这里写法有问题，感谢反馈！

**Comment by wode551120** [comment]
不客气
