### ISSUE TITLE
0.1.6版本填写有内容时，点击下拉列表不能展示所有选项

### ISSUE THREAD

**Issue by qinchz** [lzwme/bootstrap-suggest-plugin#13]
你好，有这样一个问题：

什么都不填入，会展示所有内容
![image](https://cloud.githubusercontent.com/assets/18414101/16186627/2600b412-36fe-11e6-94da-d0f13d7275d2.png)
如果选择”全部”，并再次点击下拉按钮，则只能展示出“全部”这个选项。但实际上我是需要选择其他选项，但是却看不到，我需要**手动删除**input中的内容才可重新看到所有内容。
![image](https://cloud.githubusercontent.com/assets/18414101/16186816/46652caa-36ff-11e6-9cf2-eb9b1ba491a2.png)

在0.1.2的版本中，是没有以上问题的，点击下拉可以看到全部内容的。
请问这是bug还是功能上的修改？

**Comment by renxia** [comment]
是的，实现逻辑有修改。
在0.1.2的版本中，点击下拉按钮，是不以输入框关键字作为查询。
在新的版本中，则只是触发了输入框的查询动作。
应该是 0.1.2 版本中的方式更合理一些，下一个小版本更新考虑恢复这个逻辑

**Comment by qinchz** [comment]
非常感谢，问题得到了解决~
