### ISSUE TITLE
showHeader参数设置无效

### ISSUE THREAD

**Issue by wien13** [lzwme/bootstrap-suggest-plugin#14]
当设置了这个参数effectiveFields的时候，再设置showBtn: false。貌似头还是会显示？

**Comment by renxia** [comment]
你把我搞晕了，你到底是要不显示 header 还是不显示 button 啊

**Comment by wien13** [comment]
是showHeader，我打错了。
当设置了这个参数effectiveFields的时候，再设置showHeader: false。貌似Header还是会显示？

**Comment by renxia** [comment]
已修复，请测试验证新的版本，感谢！

**Comment by wien13** [comment]
0.1.8 测试，问题确实修复了，谢谢
