### ISSUE TITLE
data数据格式问题

### ISSUE THREAD

**Issue by wien13** [lzwme/bootstrap-suggest-plugin#15]
如果通过ajax返回的json数据格式与插件要求的不一样。可以同过fnProcessData方法进行设置。
但是我发现个问题，设置好后，在UI上，点击最右侧的按钮可以正常使用，而直接在输入框里点击，会报错说数据格式不正确，我的理解是右侧的按钮使用了fnProcessData重新梳理过的数据。而文本框直接点击，没有使用fnProcessData处理过的数据。

**Comment by renxia** [comment]
确实存在逻辑问题，已修复，感谢！

**Comment by wien13** [comment]
0.1.8 测试问题已经修复，谢谢
