### ISSUE TITLE
url连接参数问题

### ISSUE THREAD

**Issue by wien13** [lzwme/bootstrap-suggest-plugin#16]
这样设置参数，json连接后面跟一个参数t，挂时间戳，防止每次get请求取到重复数据。
url: "/xx.json?t=" + (new Date()).getTime()

但是最终请求的url，为啥最后面多了一个&？
http://localhost/xx.json?t=1468554911659&

**Comment by renxia** [comment]
因为会附带输入框的关键字作为参数查询，URL 必须作修正。

另外，你这样写是没有用的，t 参数在配置时就生成了，每次请求都不会改变，并不能达到你的目的。

可以通过 fnAdjustAjaxParam 参数来实现

**Comment by wien13** [comment]
我的需求这样写还行，我不是输入关键字再搜，我是用这个url初始化直接加载数据

**Comment by wien13** [comment]
我大致理解你这样做的意思了，这个close掉吧
