### ISSUE TITLE
下拉方向自动

### ISSUE THREAD

**Issue by xylangyan** [lzwme/bootstrap-suggest-plugin#2]
Hi，可否下拉方向自动判断呢，就跟select 那样，默认下方，当下方空间不足的时候，在上方显示

**Comment by renxia** [comment]
bootstrap 下拉式菜单本身是不支持其他方向的
这个插件的目的是作为搜索输入建议而不是 select，如果展示在其他方向看上去也挺奇怪的
你觉得呢

**Comment by langyan1022** [comment]
好吧，不过bootstrap是支持 上拉的，只是不能自动，\

 <div class="btn-group dropup">
  <button type="button" class="btn btn-default">Dropup</button>
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li>aa</li>
     <li>aa</li>
     <li>aa</li>
     <li>aa</li>
  </ul>
</div>

**Comment by langyan1022** [comment]
好吧，不过bootstrap是支持 上拉的，只是不能自动，

```html
 <div class="btn-group dropup">
  <button type="button" class="btn btn-default">Dropup</button>
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li>aa</li>
     <li>aa</li>
     <li>aa</li>
     <li>aa</li>
  </ul>
</div>
```

**Comment by xylangyan** [comment]
好吧，不过bootstrap是支持 上拉的，只是不能自动，

``` html
 <div class="btn-group dropup">
  <button type="button" class="btn btn-default">Dropup</button>
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li>aa</li>
     <li>aa</li>
     <li>aa</li>
     <li>aa</li>
  </ul>
</div>
```

**Comment by renxia** [comment]
确实如此，感谢建议。
已经增加了一个 autoDropup 参数，请测试

**Comment by xylangyan** [comment]
好的，谢谢，我空了测试下
