### ISSUE TITLE
怎么通过id去设置默认值

### ISSUE THREAD

**Issue by von7750** [lzwme/bootstrap-suggest-plugin#22]
`<select class="form-control" id="cooperativeType">'
'<option value="-1">请选择</option>'
'<option value="1">我方付款</option>'
'<option value="2">对方付款</option>'
'</select>`
通过$("#cooperativeType").val(2) 就能显示为对方付款,bootstrap-suggest-plugin里该怎么做?

**Comment by renxia** [comment]
参考这个问题 #17

**Comment by von7750** [comment]
谢谢你,  昨天在里面新增了转换方法.
