### ISSUE TITLE
isInWord方法讨论

### ISSUE THREAD

**Issue by wushp** [lzwme/bootstrap-suggest-plugin#23]
当前的业务需求
1.用户输入的关键字 indexOf 维护的字典内，才能过滤出
2.反之不需要过滤出(维护的字典内 indexOf 用户输入的关键字，才能过滤出)

方案一：
//        return value &&
//            (inEffectiveFields(key, options) || inSearchFields(key, options)) &&
//            (value.indexOf(keyword) !== -1 || keyword.indexOf(value) !== -1);
        return value &&
              (inEffectiveFields(key, options) || inSearchFields(key, options)) &&
              (value.indexOf(keyword) !== -1);

方案二：
是否可以增加配置，让用户选择

**Comment by renxia** [comment]
是的，当前为了最大化的返回匹配，匹配方式是包含和被包含都计算为匹配，这和我们之前的业务需求是相关的。

按照你提的需求，可以增加一个参数配置项，以设置是否匹配被包含的情况

节后会考虑这个需求

**Comment by wushp** [comment]
谢谢~

**Comment by renxia** [comment]
已新增 `towWayMatch` 配置项，用于设置是否双向匹配。默认为 `true`
