### ISSUE TITLE
请求多个参数问题

### ISSUE THREAD

**Issue by gj452652749** [lzwme/bootstrap-suggest-plugin#25]
url: "/rest/sys/getuserlist?area='+area+'keyword="，我发现area永远是初始值，这个有办法解决吗？

**Comment by renxia** [comment]
这种情况需要使用`fnAdjustAjaxParam`参数来实现。示例：

```js
$('#test').bsSuggest({
    url: '/rest/sys/getuserlist',
    getDataMethod: 'url',
    fnAdjustAjaxParam: function(keyword, opts) {
        return {
            data: {
                keyword: keyword,
                area: area
            }
        }
    }
}
```
相关 demo:

https://github.com/lzwme/bootstrap-suggest-plugin/blob/master/demo/demo.js#L189

**Comment by gj452652749** [comment]
thanks，反馈相当速度啊，看来我得更新下这个插件了

**Comment by renxia** [comment]
欢迎关注，多提建议，有问题多反馈

**Comment by xiaofeixia** [comment]
var bsSuggest = $("#selectUnit").bsSuggest({
            getDataMethod: "url",   //获取数据的方式，总是从 URL 获取
            url: '${path}/verifylog/getUnitList.do', /*优先从url ajax 请求 json 帮助数据，注意最后一个参数为关键字请求参数*/
            effectiveFieldsAlias:{unit_no:"单位编号",unit_name: "单位名称"},
            clearable: true,
            ignorecase: true,
            showHeader: true,
            allowNoKeyword: false,
            showBtn: false,     //不显示下拉按钮
            delayUntilKeyup: true, //获取数据的方式为 firstByUrl 时，延迟到有输入/获取到焦点时才请求数据
            idField: "unit_no",
            keyField: "unit_name",
            //调整 ajax 请求参数方法，用于更多的请求配置需求。如对请求关键字作进一步处理、修改超时时间等
			fnAdjustAjaxParam: function (keyword, options) {
			    return {
			        type: 'POST',
			        data: {
			            wd: keyword
			        }
			    }
			}
            
        }).on('onDataRequestSuccess', function (e, result) {
    	    console.log('onDataRequestSuccess: ', result);
    	}).on('onSetSelectValue', function (e, keyword, data) {
    	    console.log('onSetSelectValue: ', keyword,keyword.id,keyword.key, data);
    	}).on('onUnsetSelectValue', function () {
    	    console.log("onUnsetSelectValue");
    	});
fnAdjustAjaxParam 不生效啊，请问有什么解决方案？

**Comment by renxia** [comment]
@xiaofeixia 示例代码没看出有什么问题，可能你的 `url` 参数有点问题
