### ISSUE TITLE
无法触发dataRequestSuccess事件

### ISSUE THREAD

**Issue by qinchz** [lzwme/bootstrap-suggest-plugin#26]
你好，有个问题。使用URL方式请求json数据，并且前台页面已经可以成功解析展示下拉列表，但是为什么没有触发dataRequestSuccess中的方法？
![image](https://cloud.githubusercontent.com/assets/18414101/21010069/1321c378-bd85-11e6-9e97-80cc668adffe.png)

**Comment by renxia** [comment]
调整下顺序，把 on 放前面，先监听后启动。
因为可能请求已成功而事件监听还没执行

**Comment by qinchz** [comment]
我试着放到前面，还是不可以执行呢，前台也没有报什么错
![image](https://cloud.githubusercontent.com/assets/18414101/21040616/0d444e52-be21-11e6-93cb-1e3dbcd9951d.png)

**Comment by renxia** [comment]
仔细确认了一下，是 `onDataRequestSuccess`

另外，on 监听后返回对象自身，可以继续使用链式写法

**Comment by qinchz** [comment]
好的谢谢，那么README.md文档使用就要修改一下啦。
另外一个小问题，在控件加载完成之后，我想选中默认项。此时ul列表不会展示，我需要先手动触发button按钮：
$('#jgSel').next().find('button').click();
然后才可以进行默认菜单的手动设定：
$("#jgSel").next().find('ul tbody tr:eq(0)').trigger('mousedown');
这样的使用方法是否合理？

**Comment by renxia** [comment]
设置默认值不用先触发下拉菜单按钮。后一步没有问题
可参考 #17

**Comment by qinchz** [comment]
我试了#17的方法，发现如果不先触发下拉按钮ul列表元素并不存在与页面，因此其中查找ul的方法并不可用呢

**Comment by renxia** [comment]
看了一下，`onDataRequestSuccess` 事件回调时不会触发列表的生成，确实是不存在。
可以先触发一下 click 事件，或你的方法也没有什么问题。示例：
```js
$('#test').on('onDataRequestSuccess', function() {
    $(this).click().next().find('ul tbody tr:eq(0)').trigger('mousedown');
});
```

当然这里只是一个示例。其实设置默认值的本质，就是设置 input 的值。可以有各种方式达到目的。
例如你也可以这样来做：
```js
$("#test")
    .on('onDataRequestSuccess', function (event, result) {
        $(this).val(result.value[0].userName)
            .attr('data-id', result.value[0].userId);
    });
```

**Comment by qinchz** [comment]
好的，谢谢
