### ISSUE TITLE
怎么让插件重新去加载后台的数据

### ISSUE THREAD

**Issue by gcdong** [lzwme/bootstrap-suggest-plugin#27]
首先很感谢这个贵工作室编写的这个插件

现在我在使用中遇到一个问题,就是我的插件配置好了以后,是可以正常出来数据了,但是我如果后台有数据更新,我要怎么在不刷新页面的情况下获取到新的后台数据呢?

**Comment by renxia** [comment]
设置一直从后端API获取就行啊。主要需要配置如下参数：

```js
{
    url: 'http://unionsug.baidu.com/su?p=3&wd=',
    getDataMethod: "url", //获取数据的方式，总是从 URL 获取
}
```

可以参考百度搜索/淘宝搜索的示例：
https://github.com/lzwme/bootstrap-suggest-plugin/blob/master/demo/demo.js#L116

**Comment by SummerLiJingYang** [comment]
你好,,当获取数据的方式设置为url 以后发现不会进入到下面这个事件中,,因为是想做一个基于第一个输入框才显示第二个输入框的二级联动
on('onDataRequestSuccess', function (event, result) {
        console.log(result);
    })

**Comment by SummerLiJingYang** [comment]
还有 在我关闭了一个下拉框之后 调用$("input#test").bsSuggest("destroy"); 好像没什么效果

**Comment by renxia** [comment]
@SummerLiJingYang  
你提到的第一个问题应该不存在。参考 demo 页面百度搜索示例，打开 F12 调试可以看到，每当有输入时会 `onDataRequestSuccess` 事件回调的打印输出
第二个问题描述太模糊，给出示例最好
