### ISSUE TITLE
可不可以监控“oninput”事件呢

### ISSUE THREAD

**Issue by wjs57y** [lzwme/bootstrap-suggest-plugin#28]
这个插件挺好用的，只是在输入中文的时候没有填入到输入框也会触发搜索，这样很浪费，碰到数据量大的时候会有点慢。是不是选项可以设置，没有查到？

**Comment by renxia** [comment]
有作延时处理，input 事件也有监听，不过是为了处理中文输入问题，没有作进一步优化。
你提到的问题也有思考过，正在考虑作对应的改进，感谢建议！
