### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by StrangeClow** [lzwme/bootstrap-suggest-plugin#29]
怎么从数据库中按照搜索关键词去数据库中取数据 开始只加载少量数据 10条

**Comment by renxia** [comment]
你的需求和百度搜索的示例基本一致，可参考相关部分示例代码：

https://github.com/lzwme/bootstrap-suggest-plugin/blob/master/demo/demo.js#L116

要求每次搜索都从接口获取，应当配置参数 `getDataMethod: 'url' `
至于显示多少条，是由后端返回决定的，后端返回的符合条件的数据，都会出现在选择列表中

**Comment by sysecho** [comment]
请问配置getDataMethod：firstByUrl 时，如何实现精确查找而不是包含和包含于搜索字段查询，还是说只能配置成url，然后每次从后台获取值？谢谢!
