### ISSUE TITLE
下拉菜单滚动条无法点中

### ISSUE THREAD

**Issue by yangsenbin** [lzwme/bootstrap-suggest-plugin#3]
Hi：
  我设置了"overflow": "auto" ，当我的suggest内容大于下拉菜单最大长度时，右侧出现滚动条，但是滚动条无法用鼠标点中拖动。
![image](https://cloud.githubusercontent.com/assets/15999131/11367273/84fa1306-92ed-11e5-8c07-2e4a58c22872.png)

这是在bootstrap的模态框内向input添加了suggest。

**Comment by renxia** [comment]
具体问题难以定位，简单的在 modal 中使用时没有问题的，参考示例页面。复杂情况下，可能与modal的状态、绑定的事件等有关系，点击滚动条会导致输入框失去焦点

**Comment by yangsenbin** [comment]
问题已经查明：我在modal上加了tabIndex，就会造成上述情况。去掉tabIndex之后可以点击滚动条了。
感谢！
