### ISSUE TITLE
精确查询

### ISSUE THREAD

**Issue by sysecho** [lzwme/bootstrap-suggest-plugin#30]
请问配置getDataMethod：firstByUrl 时，如何实现精确查找而不是包含和包含于搜索字段查询，还是说只能配置成url，然后每次从后台获取值？谢谢!

**Comment by renxia** [comment]
既然是搜索建议，必然是包含或包含于才有意义，否则就不需要建议列表了。
当前的搜索匹配方式可以满足绝大多数搜索建议需求，更为复杂的还是交给后端来处理好了

**Comment by sysecho** [comment]
小小建议：如果能一个加一个精确查询的控制开关就更完美了。当然这样可能与插件初衷不适，但是功能却能满足大多数场景。非常感谢回答！

**Comment by renxia** [comment]
如果需要精确查询，就不存在前端匹配，那么也没有意义啊，直接配置 `getDataMethod: 'url'` 从后端获取就好了。

可能你希望首次获取所有数据，后续精确匹配。
其实也提供了这种能力，可以重写 `fnGetData` 参数方法来实现，以自定义数据获取/匹配方式
