### ISSUE TITLE
重复发送ajax请求

### ISSUE THREAD

**Issue by MrZhangFengfeng** [lzwme/bootstrap-suggest-plugin#31]
当仅仅是点击一下搜索框，聚焦后就立刻再次发送ajax请求。能否当搜索框内容发生变化的时候才会发送请求

**Comment by renxia** [comment]
在聚焦、有按键弹起时，都会触发请求。
这种行为触发的请求应该不会太频繁(默认有 300ms 间隔限制，可以自定义)，所以没有考虑作进一步的缓存处理

**Comment by renxia** [comment]
检查了一下逻辑，相同关键词是有检测的。
但是在选则列表项后再次点击，没有对选择的值作记录，会出现重复请求的情况。
后面会作这一处的处理
