### ISSUE TITLE
when the data has been removed by backspace quickly, the data-id cannot be set to empty

### ISSUE THREAD

**Issue by antstudio-git** [lzwme/bootstrap-suggest-plugin#32]
steps:

1. select a valid data from the url request
2. remove the data by the backspace key one by one quickly

issue:
 the element attribute still have the data-id with the previous value ,like this below:

input type="text" placeholder="请选择" class="form-control" id="creator" autocomplete="off" alt="test4" data-id="6" style="background: rgb(255, 255, 255);"

**Comment by renxia** [comment]
I have no problem testing under the Chrome browser.
Can you provide the browser version?

**Comment by antstudio-git** [comment]
Chrome Version  60.0.3112.90
FireFox Latest

detail the operation:
1. it would be representd that after selecting one keyword, then press the backspace quickly for times 
2. NOT clear the keyword once a time
3. set the request for url ,not firsturl

if it could not  be  presented again, i will record the steps as gif file. 

thanks for the great plugin job.

**Comment by hkaikai** [comment]
bootstrap-suggest.js文件813行添加如下代码
`if ($.trim(word) == '') {
                        	setOrGetDataId($input, '');
                        }`

**Comment by renxia** [comment]
@hkaikai 
https://github.com/lzwme/bootstrap-suggest-plugin/blob/master/src/bootstrap-suggest.js#L781

在 keydown 事件中已经做过了 data-id 的重置，应该不会有这个问题的
我尝试了很多次都没有重现到这种现象出现

**Comment by renxia** [comment]
仔细看了一遍，应该是当下拉菜单隐藏后，再做这个操作，在 keydown 事件中是直接返回了，会存在问题
