### ISSUE TITLE
怎么通过js给suggest赋值回显呢？

### ISSUE THREAD

**Issue by kaixinwangzi1982** [lzwme/bootstrap-suggest-plugin#34]
类似select功能的setVal方法，给suggest赋值，并能触发相应的事件。
我现在这么写的$(#input).val("124").trigger("onSetSelectValue");   触发不了事件

**Comment by renxia** [comment]
只是设置输入框初始值的话你的写法就足够了。如果还需要设置 `data-id` 属性，则可以在列表加载完成后模拟输入来实现。
可参考 #17 

手动触发 `.trigger("onSetSelectValue")` 也是需要传参数才有意义

**Comment by kaixinwangzi1982** [comment]
@renxia 非常感谢哈！！！！
