### ISSUE TITLE
ie中文get搜索，建议问号后面的keyword修改成encodeURI(keyword);

### ISSUE THREAD

**Issue by hkaikai** [lzwme/bootstrap-suggest-plugin#37]
// url 调整
        ajaxParam.url = function() {
            if (!keyword || ajaxParam.data) {
                return ajaxParam.url || options.url;
            }

            var type = '?';
            if (/=$/.test(options.url)) {
                type = '';
            } else if (/\?/.test(options.url)) {
                type = '&';
            }

            return options.url + type + keyword; // return options.url + type + encodeURI(keyword);
        }();

**Comment by renxia** [comment]
有道理，后续会考虑
