### ISSUE TITLE
ie10，ie11，下拉列表自动弹出，必须选择一项才行

### ISSUE THREAD

**Issue by hkaikai** [lzwme/bootstrap-suggest-plugin#38]
keyup input paste事件对空进行处理，并return掉？！！

**Comment by renxia** [comment]
不知所云...

**Comment by zhao33699** [comment]
我遇到这个问题了  然后过来看你无情的把提问给关闭了。。。

**Comment by zhao33699** [comment]
在ie11下，插件版本为2014-10-09的版本，点击文本框，下拉菜单出现，不填写任何内容，鼠标移至下拉菜单上，文本框失去焦点，当鼠标离开下拉菜单，会自动触发文本框focus事件，此时鼠标单击，此时应该触发了blur事件，然后隐藏下拉菜单。在谷歌下没问题，但是在ie11下，会在文本框blur之前触发input事件，导致应该隐藏的下拉菜单又重新出现了。
跟踪日志：mouseleave  ->input focus->  input blur->input keyup [event.type=input](这个是在settimeout里面的)
我的解决办法：在隐藏列表的同时,注销keyupTimer延时事件
 if (!isMouseenterMenu) { // 不是进入下拉列表状态，则隐藏列表
                        $dropdownMenu.css('display', '');
                        if(keyupTimer)  clearTimeout(keyupTimer);
                    }
