### ISSUE TITLE
清空value和删除value（选择input里面的文字再全部删除），没有触发onUnsetSelectValue

### ISSUE THREAD

**Issue by hkaikai** [lzwme/bootstrap-suggest-plugin#42]

**Comment by CurryHan** [comment]
同样遇到这个问题,看了源码,作者的意思是 只有用户 在input框内自由输入的时候,才会触发这个事件。
与 onSelectValue事件想对应，选择完毕触发onSetSelectValue,如果不去选择，自由输入则会触发onUnsetSelectValue 事件。
  结论是 点击清除按钮或者手动去掉输入框的内容,都不会触发onUnsetSelectValue 。

**Comment by hkaikai** [comment]
我自己改代码了，触发onUnsetSelectValue，能用就行
