### ISSUE TITLE
当在下拉框在隐藏的情况下初始化，然后在需要的时候显示，会出现右侧清除按钮错位的问题

### ISSUE THREAD

**Issue by Amir-Lee** [lzwme/bootstrap-suggest-plugin#46]
![Uploading 下拉按钮清除按钮错误.png…]()

@renxia 
经分析确认在隐藏的情况下，$input.next('.input-group-btn').width()会出现为1的情况。
建议处理方法改为：
return $iClear.css({
            position: 'absolute',
            top: 12,
            right: options.showBtn ? ($input.next('.input-group-btn').width()==1?33:($input.next('.input-group-btn').width() || 33)) + 2 : 12,
            zIndex: 4,
            cursor: 'pointer',
            fontSize: 12
        }).hide();
或
return $iClear.css({
            position: 'absolute',
            top: 12,
            right: options.showBtn ? Math.max(($input.next('.input-group-btn').width() || 33),33)+ 2 : 12,
            zIndex: 4,
            cursor: 'pointer',
            fontSize: 12
        }).hide();

**Comment by renxia** [comment]
是可以这么兼容一下
隐藏的情况下得不到实际的宽度，所以 33 是针对 bs3 的一个兼容。
但对于 bs4 来说可能还是会有问题的
