### ISSUE TITLE
如果想要分页怎么处理

### ISSUE THREAD

**Issue by neozhu** [lzwme/bootstrap-suggest-plugin#49]
毕竟当加载大量数据会比较慢，要考虑到分页加载，但这样也会有一个问题，就是当作为编辑页面控件出现的时候，数据还没有加载(但初始化值data_id已经给定又不再第一页，需要触发一次查询才能知道对应的显示名称时)要怎么处理呢

**Comment by renxia** [comment]
大数据量建议做服务器查询返回 topN 条，如百度、淘宝搜索，但最多只给出前十条关键词建议结果
已知 id 的情况，可以要求后端做接口查询处理，通过 `fnPreprocessKeyword` 参数，初始化时传入查询其单个信息即是
