### ISSUE TITLE
IE内核下下拉滚动条无法点中

### ISSUE THREAD

**Issue by yangsenbin** [lzwme/bootstrap-suggest-plugin#6]
hi 
我在IE 11下发现demo中的例子：
测试(首次从 URL 获取数据) 
测试(首次从 URL 获取数据，不显示按钮)
中的下拉滚动条无法点中

**Comment by renxia** [comment]
确实，考虑兼容中

**Comment by renxia** [comment]
已作兼容修改，请测试验证 IE8 - IE11

**Comment by yangsenbin** [comment]
OK了，感谢！
另外，86行有一个拼写错误“window.console.tarce”

**Comment by wolfee9633** [comment]
你好，有一个问题就是firefox下，搜索框中输入时无法实时更新下拉建议框（例如：测试(首次从 URL 获取数据，不显示按钮)），在ie和chrome下没有该问题
