### ISSUE TITLE
没有自定义搜索的方法

### ISSUE THREAD

**Issue by yixiaco** [lzwme/bootstrap-suggest-plugin#64]
有一些，例如腾讯地图的地理位置搜索需要特定的加载数据方法，不能使用ajax，或其他方式，会产生跨域访问问题，这时怎么操作？

**Comment by renxia** [comment]
通过自定义 getData 参数，是可以实现自定义加载数据的方法的

一般这种第三方服务应该会提供配置了 token 的跨域搜索的。
如果跨域问题解决不了，可以自己在服务器做一下转发
