### ISSUE TITLE
进行销毁时 会把 文本框的绑定事件一并给off了

### ISSUE THREAD

**Issue by cookieless** [lzwme/bootstrap-suggest-plugin#67]

**Comment by renxia** [comment]
是的，事件销毁时只是简单的off其全部事件绑定。该问题后续会作优化
不过一般不建议对输入框做其他额外的事件绑定，可能出现怪异现象
另外一般也很少会需要对其做销毁或反复初始化。如果逻辑流程里有这样的需求，可以通过检测 `$('input').data('bsSuggest')` 是否存在，来决定是否需要对其做初始化
