### ISSUE TITLE
如何实现二级联动？

### ISSUE THREAD

**Issue by yongahua** [lzwme/bootstrap-suggest-plugin#68]
项目要求实现选中省，另一个自动变为该省下的市区，可是进入页面后第一次加载完，点击省后，市区对应的下拉没法再次渲染，怎么才能二次渲染？

**Comment by renxia** [comment]
用这个来实现二级联动其实不太推荐。不过也有实现方法。
在 `onHideDropdown` 或 `onSetSelectValue` 事件发生时，处理获得二级联动的数据，然后销毁并重新初始化二级联动下拉组件
