### ISSUE TITLE
不使用url使用data时，表头显示顺序是依据data中第一个的顺序显示

### ISSUE THREAD

**Issue by C-Y-T** [lzwme/bootstrap-suggest-plugin#69]
在不改变data的情况下，有办法解决吗？
配置：
effectiveFields: ["name",,'value'],
effectiveFieldsAlias:  {
         name: "字段",
          value:'值'
    },
data: {value:[
  {
    name:"111",
    value: "v1"
  },
  {
    value:"v1",
    name: 222
  },
  {
    value:"v1",
    name: 333
  }
]},

显示：
![image](https://user-images.githubusercontent.com/55471042/98763062-22fec580-2414-11eb-910d-7cb43cc6a352.png)

**Comment by renxia** [comment]
实际上是依据 `effectiveFields` 定义的顺序显示的
