### ISSUE TITLE
分页

### ISSUE THREAD

**Issue by sky0504** [lzwme/bootstrap-suggest-plugin#7]
数据过多时，能否支持分页

**Comment by renxia** [comment]
暂时没有考虑分页。作为搜索建议组件，一般不建议数据太多。太多的话应当服务器端分页实时查询，然后返回前十是比较合适的。

**Comment by sky0504** [comment]
考虑到如果有100条数据的话，每页显示10条数据，总共10页显示出来。如果全部下拉选择的话，不是特别容易选到。分页就很容易定位到你想要的那条数据了

其实就类似输入法的显示效果。
