### ISSUE TITLE
下拉列表为什么会展示index的值？

### ISSUE THREAD

**Issue by qinchz** [lzwme/bootstrap-suggest-plugin#9]
你好，请问这个问题如何解决：
一、单击input，选中第一项
![image](https://cloud.githubusercontent.com/assets/18414101/14451658/691b90e2-00bb-11e6-8e7d-a2539f9fef23.png)
二、再单击input，下拉列表中会自动新增最后一列index的值
![image](https://cloud.githubusercontent.com/assets/18414101/14451675/8805a74a-00bb-11e6-81ca-e19001e3bf2a.png)

看您的demo页面就不会这样，是什么问题呢

**Comment by renxia** [comment]
之前的版本存在bug，更新为最新的版本再试试

**Comment by qinchz** [comment]
谢谢，更新之后的确好了
